#!/usr/bin/env python3
"""starsnapshot - GitHub starred repositories snapshot & report generator.

Pure standard-library CLI tool. Fetches a GitHub user's starred
repositories, aggregates statistics and writes a Markdown report.
"""

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import Any

API_BASE = "https://api.github.com"
PER_PAGE = 100
USER_AGENT = "starsnapshot/1.0 (+https://github.com/Miku-3993/starsnapshot)"


def build_headers() -> dict[str, str]:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": USER_AGENT,
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def http_get_json(url: str, headers: dict[str, str]) -> Any:
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            raise ValueError(f"user not found: {url}") from exc
        if exc.code == 403 and exc.headers.get("X-RateLimit-Remaining") == "0":
            raise RuntimeError("GitHub API rate limit exceeded") from exc
        raise


def fetch_starred(username: str, headers: dict[str, str]) -> list[dict[str, Any]]:
    starred: list[dict[str, Any]] = []
    page = 1
    while True:
        url = f"{API_BASE}/users/{username}/starred?per_page={PER_PAGE}&page={page}"
        data = http_get_json(url, headers)
        if not data:
            break
        starred.extend(data)
        if len(data) < PER_PAGE:
            break
        page += 1
        time.sleep(0.05)  # be gentle with the API
    return starred


def aggregate(starred: list[dict[str, Any]]) -> dict[str, Any]:
    by_lang: dict[str, int] = {}
    for repo in starred:
        lang = repo.get("language") or "(none)"
        by_lang[lang] = by_lang.get(lang, 0) + 1

    top_stars = sorted(
        starred, key=lambda r: r.get("stargazers_count", 0), reverse=True
    )[:10]
    recent = sorted(
        starred,
        key=lambda r: r.get("starred_at") or "",
        reverse=True,
    )[:10]
    return {
        "total": len(starred),
        "by_lang": sorted(by_lang.items(), key=lambda kv: kv[1], reverse=True),
        "top_stars": top_stars,
        "recent": recent,
    }


def render(username: str, stats: dict[str, Any]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# ⭐ Star Snapshot: @{username}",
        "",
        f"*Generated on {now}*",
        "",
        f"**Total starred repositories: {stats['total']}**",
        "",
        "## By language",
        "",
        "| Language | Repos |",
        "|----------|------:|",
    ]
    for lang, count in stats["by_lang"] or [("(none)", 0)]:
        lines.append(f"| {lang} | {count} |")
    lines += ["", "## Top 10 by stars", ""]
    if stats["top_stars"]:
        for i, repo in enumerate(stats["top_stars"], 1):
            lines.append(
                f"{i}. [{repo['full_name']}]({repo['html_url']}) "
                f"⭐{repo['stargazers_count']}"
            )
    else:
        lines.append("_No starred repositories yet._")
    lines += ["", "## Recently starred", ""]
    if stats["recent"]:
        for repo in stats["recent"]:
            lines.append(f"- [{repo['full_name']}]({repo['html_url']})")
    else:
        lines.append("_No starred repositories yet._")
    lines += [
        "",
        "---",
        "*Report generated by "
        "[starsnapshot](https://github.com/Miku-3993/starsnapshot)*",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="GitHub star snapshot generator")
    parser.add_argument("username", help="GitHub username to snapshot")
    parser.add_argument("--out", default="stars.md", help="output markdown file (default: stars.md)")
    args = parser.parse_args()

    headers = build_headers()
    try:
        starred = fetch_starred(args.username, headers)
        report = render(args.username, aggregate(starred))
    except (ValueError, RuntimeError, urllib.error.URLError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(report)
    print(f"OK: wrote {args.out} ({len(starred)} repos)")
    return 0


if __name__ == "__main__":
    sys.exit(main())